import os
import json

# Paths Configuration
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
SEQUENCES_DIR = os.path.join(BASE_DIR, "sequences")
OUTPUT_HEADER_PATH = os.path.join(BASE_DIR, "pebble_haptic_composer", "presets_data.h")

# Ensure sequences directory exists
os.makedirs(SEQUENCES_DIR, exist_ok=True)

# Map filenames to protocol names
PROTOCOLS = {
    "box": "BOX",
    "sleep": "SLEEP",
    "relax": "RELAX",
    "presence": "PRESENCE"
}

def parse_json_sequence(filepath):
    """
    Parses a sequence JSON file and returns a sorted list of events and total duration.
    """
    if not os.path.exists(filepath):
        print(f"[!] Warning: Sequence file not found: {filepath}. Generating fallback empty sequence.")
        return [], 10000

    try:
        with open(filepath, 'r') as f:
            data = json.load(f)
        
        duration = data.get("totalDuration", 10000)
        tracks = data.get("tracks", {})
        
        events = []
        
        # Parse Left Track (L)
        for node in tracks.get("L", []):
            events.append({
                "timeMs": node.get("startTime", 0),
                "track": "L",
                "presetId": node.get("presetId", 1)
            })
            
        # Parse Right Track (R)
        for node in tracks.get("R", []):
            events.append({
                "timeMs": node.get("startTime", 0),
                "track": "R",
                "presetId": node.get("presetId", 1)
            })
            
        # Sort chronologically by millisecond offset
        events.sort(key=lambda x: x["timeMs"])
        return events, duration

    except Exception as e:
        print(f"[ERROR] Failed to parse {filepath}: {e}")
        return [], 10000

def generate_header():
    print("=======================================================")
    print(" Pebble Firmware Pacer Compiler: Compiling JSON DAW sequences...")
    print("=======================================================")
    
    header_content = []
    header_content.append("/**")
    header_content.append(" * =============================================================================")
    header_content.append(" * presets_data.h - AUTO-GENERATED BY compile_presets SCRIPT")
    header_content.append(" * =============================================================================")
    header_content.append(" * This file contains high-performance PROGMEM (Flash memory) structural arrays")
    header_content.append(" * representing the exact timeline sequences sculpted inside your web DAW.")
    header_content.append(" * Do not edit this file manually.")
    header_content.append(" * =============================================================================")
    header_content.append(" */")
    header_content.append("")
    header_content.append("#ifndef PRESETS_DATA_H")
    header_content.append("#define PRESETS_DATA_H")
    header_content.append("")
    header_content.append("#include <Arduino.h>")
    header_content.append("")
    header_content.append("// --- UNIFIED PACER STRUCT ---")
    header_content.append("struct PresetEvent {")
    header_content.append("  unsigned long timeMs;")
    header_content.append("  char track;")
    header_content.append("  byte presetId;")
    header_content.append("};")
    header_content.append("")

    for filename, prefix in PROTOCOLS.items():
        json_path = os.path.join(SEQUENCES_DIR, f"{filename}.json")
        events, duration = parse_json_sequence(json_path)
        
        header_content.append(f"// --- {prefix} BREATHING PACER ---")
        header_content.append(f"const unsigned long {prefix}_DURATION = {duration}UL;")
        header_content.append(f"const int {prefix}_EVENT_COUNT = {len(events)};")
        
        if len(events) == 0:
            # Fallback empty structural array
            header_content.append(f"const PresetEvent {prefix}_EVENTS[1] PROGMEM = {{")
            header_content.append("  { 0, 'L', 0 }")
            header_content.append("};")
        else:
            header_content.append(f"const PresetEvent {prefix}_EVENTS[{len(events)}] PROGMEM = {{")
            for idx, ev in enumerate(events):
                comma = "," if idx < len(events) - 1 else ""
                header_content.append(f"  {{ {ev['timeMs']}UL, '{ev['track']}', {ev['presetId']} }}{comma}")
            header_content.append("};")
        header_content.append("")

    header_content.append("#endif // PRESETS_DATA_H")
    header_content.append("")

    with open(OUTPUT_HEADER_PATH, 'w') as f:
        f.write("\n".join(header_content))

    print(f"[SUCCESS] Compiled presets. Static header updated at: {OUTPUT_HEADER_PATH}")

if __name__ == "__main__":
    generate_header()
